config/routes.rb
# frozen_string_literal: true

Passkit::Engine.routes.draw do
  scope :api, constraints: {pass_type_id: /.*/} do
    scope :v1 do
      resources :devices, only: [] do
        post "registrations/:pass_type_id/:serial_number" => "api/v1/registrations#create", :as => :register
        delete "registrations/:pass_type_id/:serial_number" => "api/v1/registrations#destroy", :as => :unregister
        get "registrations/:pass_type_id" => "api/v1/registrations#show", :as => :registrations
      end
      get "passes/:pass_type_id/:serial_number" => "api/v1/passes#show", :as => :pass
      get "passes/:payload", to: "api/v1/passes#create", as: :passes_api
      post "log" => "api/v1/logs#create", :as => :log
    end
  end

  namespace :dashboard do
    resources :previews, only: [:index, :show], param: :class_name
    resources :logs, only: [:index]
    resources :passes, only: [:index]
  end
end

app/controllers/passkit/dashboard/application_controller.rb
module Passkit
  module Dashboard
    class ApplicationController < ActionController::Base
      layout "passkit/application"

      before_action :_authenticate_dashboard!

      private

      def _authenticate_dashboard!
        instance_eval(&Passkit.configuration.authenticate_dashboard_with)
      end
    end
  end
end

app/controllers/passkit/dashboard/logs_controller.rb
module Passkit
  module Dashboard
    class LogsController < ApplicationController
      def index
        @logs = Passkit::Log.order(created_at: :desc).first(100)
      end
    end
  end
end

app/controllers/passkit/dashboard/passes_controller.rb
module Passkit
  module Dashboard
    class PassesController < ApplicationController
      def index
        @passes = Passkit::Pass.order(created_at: :desc).includes(:devices).first(100)
      end
    end
  end
end

app/controllers/passkit/dashboard/previews_controller.rb
module Passkit
  module Dashboard
    class PreviewsController < ApplicationController
      def index
      end

      def show
        builder = Passkit.configuration.available_passes[params[:class_name]]
        path = Factory.create_pass(params[:class_name].constantize, builder.call)

        send_file path, type: "application/vnd.apple.pkpass", disposition: "attachment", filename: "pass.pkpass"
      end
    end
  end
end

app/views/passkit/dashboard/previews/index.html.erb
<header>
  <h1>Passkit Previews</h1>
  <%= render 'shared/passkit/navigation' %>
</header>
<main>
  <p>Here you can generate a Pass from the ones available. Configure your available passes with:</p>
  <pre>
  Passkit.configure do |config|
    config.available_passes['Passkit::YourPass'] = -> { FactoryBot.create(:user) }
  end
</pre>
  <p>Where you specify the class name as key and a function to generate a builder,
    that will be passed used to generte the Pass</p>

  <% Passkit.configuration.available_passes.each do |pass_class_name, _builder_function| %>
    <article>
      <h2><%= pass_class_name %></h2>
      <%= link_to 'Generate and download', dashboard_preview_path(pass_class_name) %>
    </article>
  <% end %>
</main>